services:
     _defaults:
          autowire: true      # Automatically injects dependencies in your services.
          autoconfigure: true # Automatically registers your services as commands, event subscribers, etc

#     Strictify\Goodies\Controller\:
#          resource: '../../Controller'
#          tags: ['controller.service_arguments']
#          autowire: true


     Strictify\Goodies\Goodies\FiltersPassThru\RouterDecorator:
          decorates: "router"

     Strictify\Goodies\Goodies\DynamicForm\FormFactoryDecorator:
          decorates: "form.factory"

     Strictify\Goodies\Goodies\DynamicForm\DynamicFormExtension:
        tags:
            - { name: 'form.type_extension', priority: 1 }

     Strictify\Goodies\Goodies\FormAction\AddFormActionExtension: ~

     Strictify\Goodies\Goodies\StreamBuilder\StreamBuilder: ~
